// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnSrQx4Wkg096bvp2wyfRmAS_jcdNCJ6U',
    appId: '1:856711818689:web:eeb7b1ac1a3fed49315340',
    messagingSenderId: '856711818689',
    projectId: 'floodguard-974ca',
    authDomain: 'floodguard-974ca.firebaseapp.com',
    storageBucket: 'floodguard-974ca.appspot.com',
    measurementId: 'G-WSJZ3KVJV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7NPnbfC2ebN_cBYWbZbaUOn7ASknIDuk',
    appId: '1:856711818689:android:f9b280b35ba0c346315340',
    messagingSenderId: '856711818689',
    projectId: 'floodguard-974ca',
    storageBucket: 'floodguard-974ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFVFJS0AQCkcvsPB0R2N-J-8Tmnj_s-sM',
    appId: '1:856711818689:ios:12db1c1ee46ed81b315340',
    messagingSenderId: '856711818689',
    projectId: 'floodguard-974ca',
    storageBucket: 'floodguard-974ca.appspot.com',
    iosBundleId: 'com.example.floodGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFVFJS0AQCkcvsPB0R2N-J-8Tmnj_s-sM',
    appId: '1:856711818689:ios:9935be88b738c1a3315340',
    messagingSenderId: '856711818689',
    projectId: 'floodguard-974ca',
    storageBucket: 'floodguard-974ca.appspot.com',
    iosBundleId: 'com.example.floodGuard.RunnerTests',
  );
}
